name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "fix: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug!
        
        **Note:** The title will automatically start with "fix:" - please add your bug description after it.
        Example: `fix: App crashes when exporting empty favorites list`

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What happened?
      placeholder: The app crashes when...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: The app should...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Open the app
        2. Click on...
        3. See error
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide your system details
      placeholder: |
        - macOS Version: 15.1
        - App Version: 1.1.0
        - Installation Method: Direct download / Built from source
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs or Error Messages
      description: Please paste any relevant logs or error messages
      placeholder: |
        ```
        Error: ...
        ```
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or videos
    validations:
      required: false
