name: 📚 Documentation
description: Suggest improvements to documentation
title: "docs: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation!
        
        **Note:** The title will automatically start with "docs:" - please add your description after it.
        Example: `docs: Add folder feature usage guide`

  - type: dropdown
    id: doc_type
    attributes:
      label: Documentation Type
      description: What kind of documentation needs improvement?
      options:
        - README.md
        - Code comments
        - API documentation
        - User guide / tutorial
        - Contributing guide
        - Other
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Current State
      description: What is missing or unclear in the current documentation?
      placeholder: The README doesn't explain...
    validations:
      required: true

  - type: textarea
    id: improvement
    attributes:
      label: Proposed Improvement
      description: What would you like to see added or changed?
      placeholder: Add a section that explains...
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, examples, or references
    validations:
      required: false
